services:
  jeonbuk-ai:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: customui
    environment:
      - DATABASE_URL=postgresql://admin:wjsqnrai@220.124.155.35:5432/customui
      - CORS_ALLOW_ORIGIN=https://ai.jb.go.kr;http://ai.jb.go.kr
    volumes:
      - open-webui:/app/backend/data
    expose:
      - "8080"
    restart: unless-stopped
    networks:
      - customui

  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    depends_on:
      - jeonbuk-ai
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    networks:
      - customui

volumes:
  open-webui: {}

networks:
  customui:
    driver: bridge

